version: "3.3"

services:
  servidor_mysql:
    hostname: mysql_project
    container_name: mysql_project
    image: mysql:5.7.40
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./dados_mysql:/var/lib/mysql:rw
      - ./deploy/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Sao_Paulo
    env_file:
      - .env